### ISSUE TITLE
application crashing due to undefined header values

### ISSUE THREAD

**Issue by saurabhsethi1102** [leoek/fetch-to-curl#52]
While calling the fetchToCurl method with url and options, if the options is having undefined value in json, then while converting it into the curl, it will break while using replace method and as the exception is not handled, it is not getting caught leading to crashing of the application

**Comment by leoek** [comment]
Hi @saurabhsethi1102 thanks for reporting the issue. With which version did you encounter the issue? From my understanding this was already fixed with the [release 0.6.0](https://github.com/leoek/fetch-to-curl/releases/tag/0.6.0).

I also tried to reproduce the issue, but was unable to do so:
<img width="1512" alt="Screenshot 2023-10-17 at 15 30 04" src="https://github.com/leoek/fetch-to-curl/assets/9424038/5a43592c-a2b4-400a-b7b7-6ce43de7bc9d">

If you can still reproduce the issue with v0.6.0, can you please add some steps to reproduce?

**Comment by saurabhsethi1102** [comment]
Hi @leoek 
Looks like I was using the older version only and now with new version it works, Will try to get into it and if I find any issue will report otherwise everything looks perfect now.
